apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zoneawarepoddisruptionbudgets.rollout-operator.grafana.com
spec:
  group: rollout-operator.grafana.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxUnavailable:
                  type: integer
                  minimum: 0
                maxUnavailablePercentage:
                  type: integer
                  minimum: 0
                  maximum: 100
                selector:
                  type: object
                  description: A selector for finding StatefulSets which span all the zones of a rollout group
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                podNamePartitionRegex:
                  type: string
                  description: A regular expression for returning a partition name given a pod name. This field is optional and should only be used when the PDB is to be scoped to a zone and partition, such as a multi-zone ingester deployment with ingest_storage_enabled. Enabling this changes the PDBZ functionality such that minAvailability is applied across ALL StatefulSets for a given partition. When not enabled, the minAvailability is applied to all pods in OTHER zones. The regex can be suffixed with an optional grouping. If the partition name is in group 2 then add a suffix of ",$2"
      subresources:
        status: {}
  scope: Namespaced
  names:
    kind: ZoneAwarePodDisruptionBudget
    plural: zoneawarepoddisruptionbudgets
    singular: zoneawarepoddisruptionbudget
    shortNames:
      - pdbz