apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poddisruptionzonebudgets.rollout-operator.grafana.com
spec:
  group: rollout-operator.grafana.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxUnavailable:
                  type: integer
                  minimum: 0
                maxUnavailablePercentage:
                  type: integer
                  minimum: 0
                  maximum: 100
                selector:
                  type: object
                  description: A selector for finding StatefulSets which span all the zones of a rollout group
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                podNamePartitionRegex:
                  type: string
                  description: A regular expression for returning the partition name based off a pod name. This field is optional and should only be used when the PDB is scoped to a zone and partition such as a Sigyn ingestor environment.
      subresources:
        status: {}
  scope: Namespaced
  names:
    kind: PodDisruptionZoneBudget
    plural: poddisruptionzonebudgets
    singular: poddisruptionzonebudget
    shortNames:
      - pdbz