apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-eviction-rollout-operator-development
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: rollout-operator-development
webhooks:
  - name: pod-eviction-rollout-operator-development.grafana.com
    clientConfig:
      service:
        namespace: rollout-operator-development
        name: rollout-operator
        path: /admission/pod-eviction
        port: 443
    rules:
      - operations:
          - CREATE
        apiGroups:
          -
        apiVersions:
          - v1
        resources:
          - pods/eviction
        scope: Namespaced

    admissionReviewVersions:
      - v1
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: rollout-operator-development
    failurePolicy: Fail
    sideEffects: None
