apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: rollout-operator-development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger
  template:
    metadata:
      name: jaeger
      labels:
        name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
