apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: rollout-operator-development
spec:
  selector:
    name: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: http
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: otlp-http
  type: ClusterIP
