apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: no-downscale-rollout-operator-development
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: rollout-operator-development
webhooks:
  - name: no-downscale-rollout-operator-development.grafana.com
    clientConfig:
      service:
        namespace: rollout-operator-development
        name: rollout-operator
        path: /admission/no-downscale
        port: 443
    rules:
      - operations:
          - UPDATE
        apiGroups:
          - apps
        apiVersions:
          - v1
        resources:
          - statefulsets
          - deployments
          - replicasets
          - statefulsets/scale
          - deployments/scale
          - replicasets/scale
        scope: Namespaced
    admissionReviewVersions:
      - v1
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: rollout-operator-development
    failurePolicy: Fail
    sideEffects: None
