apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: prepare-downscale-rollout-operator-development
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: rollout-operator-development
webhooks:
  - name: prepare-downscale-rollout-operator-development.grafana.com
    clientConfig:
      service:
        namespace: rollout-operator-development
        name: rollout-operator
        path: /admission/prepare-downscale
        port: 443
    rules:
      - operations:
          - UPDATE
        apiGroups:
          - apps
        apiVersions:
          - v1
        resources:
          - statefulsets
          - statefulsets/scale
        scope: Namespaced
    admissionReviewVersions:
      - v1
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: rollout-operator-development
    failurePolicy: Fail
    sideEffects: NoneOnDryRun
    matchPolicy: Equivalent
    timeoutSeconds: 10
