apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-operator
  namespace: rollout-operator-development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rollout-operator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  minReadySeconds: 10
  template:
    metadata:
      name: rollout-operator
      labels:
        name: rollout-operator
    spec:
      serviceAccountName: rollout-operator
      containers:
        - name: rollout-operator
          image: rollout-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - -kubernetes.namespace=rollout-operator-development
            - -reconcile.interval=1s
            - -log.level=debug
            - -server-tls.enabled=true
            - -server-tls.self-signed-cert.secret-name=certificate
          ports:
            - containerPort: 8001
              name: http-metrics
          readinessProbe:
            initialDelaySeconds: 1
            timeoutSeconds: 1
            httpGet:
              port: 8001
              path: /ready
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://jaeger.rollout-operator-development.svc.cluster.local.:4318/v1/traces
      restartPolicy: Always
