apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-webhook-role
  namespace: rollout-operator-development
rules:
  - apiGroups:
      -
    resources:
      - secrets
    verbs:
      - update
      - get
    resourceNames:
      - certificate
  - apiGroups:
      -
    resources:
      - secrets
    verbs:
      - create
