apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-role
  namespace: rollout-operator-development
rules:
  - apiGroups:
      -
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    verbs:
      - update
