apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: zpdb-validation-rollout-operator-development
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: rollout-operator-development
webhooks:
- name: zpdb-validation-rollout-operator-development.grafana.com
  clientConfig:
    service:
      namespace: rollout-operator-development
      name: rollout-operator
      path: /admission/zpdb-validation
      port: 443
  rules:
  - operations:
      - CREATE
      - UPDATE
    apiGroups:
      - rollout-operator.grafana.com
    apiVersions:
      - v1
    resources:
      - zoneawarepoddisruptionbudgets
    scope: Namespaced
  admissionReviewVersions: ["v1"]
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: rollout-operator-development
  failurePolicy: Fail
  sideEffects: None