apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-operator
  namespace: default
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: replicatemplates.rollout-operator.grafana.com
spec:
  group: rollout-operator.grafana.com
  names:
    categories:
    - all
    kind: ReplicaTemplate
    plural: replicatemplates
    singular: replicatemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status replicas
      jsonPath: .status.replicas
      name: StatusReplicas
      type: string
    - description: Spec replicas
      jsonPath: .spec.replicas
      name: SpecReplicas
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              labelSelector:
                type: string
              replicas:
                default: 1
                minimum: 0
                type: integer
            type: object
          status:
            properties:
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .spec.labelSelector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-operator-default-webhook-cert-update-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-operator-default-webhook-cert-secret-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-operator-default-webhook-cert-update-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - get
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
- apiGroups:
  - rollout-operator.grafana.com
  resources:
  - zoneawarepoddisruptionbudgets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-webhook-cert-secret-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - rollout-operator-self-signed-certificate
  resources:
  - secrets
  verbs:
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-operator-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-operator-webhook-cert-secret-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-operator-webhook-cert-secret-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-operator
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    name: rollout-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-operator
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rollout-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: rollout-operator
    spec:
      containers:
      - args:
        - -kubernetes.namespace=default
        - -server-tls.enabled=true
        - -use-zone-tracker=true
        - -zone-tracker.config-map-name=rollout-operator-zone-tracker
        image: grafana/rollout-operator:v0.32.0
        imagePullPolicy: IfNotPresent
        name: rollout-operator
        ports:
        - containerPort: 8001
          name: http-metrics
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: rollout-operator
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: prepare-downscale-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/prepare-downscale
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: prepare-downscale-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - statefulsets
    - statefulsets/scale
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: no-downscale-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/no-downscale
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: no-downscale-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - statefulsets
    - statefulsets/scale
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: pod-eviction-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/pod-eviction
      port: 443
  failurePolicy: Fail
  name: pod-eviction-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods/eviction
    scope: Namespaced
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: zpdb-validation-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/zpdb-validation
      port: 443
  failurePolicy: Fail
  name: zpdb-validation-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - rollout-operator.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zoneawarepoddisruptionbudgets
    scope: Namespaced
  sideEffects: None
---
apiVersion: rollout-operator.grafana.com/v1
kind: ZoneAwarePodDisruptionBudget
metadata:
  labels:
    name: ingester-rollout
  name: ingester-rollout
  namespace: default
spec:
  maxUnavailable: 1
  podNamePartitionRegex: '[a-z\-]+-zone-[a-z]-([0-9]+)'
  podNameRegexGroup: 1
  selector:
    matchLabels:
      rollout-group: ingester
