apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-operator
  namespace: default
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: replicatemplates.rollout-operator.grafana.com
spec:
  group: rollout-operator.grafana.com
  names:
    categories:
    - all
    kind: ReplicaTemplate
    plural: replicatemplates
    singular: replicatemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status replicas
      jsonPath: .status.replicas
      name: StatusReplicas
      type: string
    - description: Spec replicas
      jsonPath: .spec.replicas
      name: SpecReplicas
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              labelSelector:
                type: string
              replicas:
                default: 1
                minimum: 0
                type: integer
            type: object
          status:
            properties:
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .spec.labelSelector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zoneawarepoddisruptionbudgets.rollout-operator.grafana.com
spec:
  group: rollout-operator.grafana.com
  names:
    kind: ZoneAwarePodDisruptionBudget
    plural: zoneawarepoddisruptionbudgets
    shortNames:
    - zpdb
    singular: zoneawarepoddisruptionbudget
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              maxUnavailable:
                description: The number of pods that can be unavailable within a zone
                  or partition.
                minimum: 0
                type: integer
              maxUnavailablePercentage:
                description: Calculate the maxUnavailable value as a percentage of
                  the StatefulSet's spec.Replica count. This option is not supported
                  when using podNamePartitionRegex.
                maximum: 100
                minimum: 0
                type: integer
              podNamePartitionRegex:
                description: A regular expression for returning a partition name given
                  a pod name. This field is optional and should only be used when
                  the ZoneAwarePodDisruptionBudget is to be scoped to a partition,
                  such as a multi-zone ingester deployment with ingest_storage_enabled.
                  Enabling this changes the ZPDB functionality such that minAvailability
                  is applied across ALL zones for a given partition. When not enabled,
                  the minAvailability is applied to pods within the eviction zone
                  assuming there are no disruptions in the other zones.
                type: string
              podNameRegexGroup:
                description: The regular expression capture group number that contains
                  the partition name. This field is only required when the podNamePartitionRegex
                  field is set and has more then one grouping. The default value is
                  1 and 1-based indexing is used.
                minimum: 1
                type: integer
              selector:
                description: A selector for finding pods and statefulsets that this
                  ZoneAwarePodDisruptionBudget applies to.
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
            required:
            - selector
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-operator-default-webhook-cert-update-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-operator-default-webhook-cert-secret-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-operator-default-webhook-cert-update-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - get
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
- apiGroups:
  - rollout-operator.grafana.com
  resources:
  - zoneawarepoddisruptionbudgets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-operator-webhook-cert-secret-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - rollout-operator-self-signed-certificate
  resources:
  - secrets
  verbs:
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-operator-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-operator-webhook-cert-secret-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-operator-webhook-cert-secret-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-operator
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    name: rollout-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-operator
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rollout-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: rollout-operator
    spec:
      containers:
      - args:
        - -kubernetes.namespace=default
        - -server-tls.enabled=true
        - -use-zone-tracker=true
        - -zone-tracker.config-map-name=rollout-operator-zone-tracker
        image: grafana/rollout-operator:v0.32.0
        imagePullPolicy: IfNotPresent
        name: rollout-operator
        ports:
        - containerPort: 8001
          name: http-metrics
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: rollout-operator
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: prepare-downscale-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/prepare-downscale
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: prepare-downscale-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - statefulsets
    - statefulsets/scale
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: no-downscale-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/no-downscale
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: no-downscale-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - statefulsets
    - statefulsets/scale
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: pod-eviction-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/pod-eviction
      port: 443
  failurePolicy: Ignore
  name: pod-eviction-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods/eviction
    scope: Namespaced
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    grafana.com/inject-rollout-operator-ca: "true"
    grafana.com/namespace: default
  name: zpdb-validation-default
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rollout-operator
      namespace: default
      path: /admission/zpdb-validation
      port: 443
  failurePolicy: Ignore
  name: zpdb-validation-default.grafana.com
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
  - apiGroups:
    - rollout-operator.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zoneawarepoddisruptionbudgets
    scope: Namespaced
  sideEffects: None
