version: "2"
run:
  build-tags:
    - requires_docker
linters:
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/grafana/rollout-operator)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
